# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyUartMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyUART(object):
    def setupUi(self, MyUART):
        MyUART.setObjectName("MyUART")
        MyUART.resize(802, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Tool Button/resources/assistant.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MyUART.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MyUART)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_readOrWrite = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_readOrWrite.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Tool Button/resources/read.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_readOrWrite.setIcon(icon1)
        self.pushButton_readOrWrite.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_readOrWrite.setFlat(True)
        self.pushButton_readOrWrite.setObjectName("pushButton_readOrWrite")
        self.horizontalLayout.addWidget(self.pushButton_readOrWrite)
        self.pushButton_startOrStop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_startOrStop.setToolTip("")
        self.pushButton_startOrStop.setToolTipDuration(-1)
        self.pushButton_startOrStop.setStyleSheet("")
        self.pushButton_startOrStop.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Tool Button/resources/stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_startOrStop.setIcon(icon2)
        self.pushButton_startOrStop.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_startOrStop.setFlat(True)
        self.pushButton_startOrStop.setObjectName("pushButton_startOrStop")
        self.horizontalLayout.addWidget(self.pushButton_startOrStop)
        self.pushButton_send = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_send.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Tool Button/resources/send.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_send.setIcon(icon3)
        self.pushButton_send.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_send.setFlat(True)
        self.pushButton_send.setObjectName("pushButton_send")
        self.horizontalLayout.addWidget(self.pushButton_send)
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Tool Button/resources/clear.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_clear.setIcon(icon4)
        self.pushButton_clear.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_clear.setFlat(True)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.horizontalLayout.addWidget(self.pushButton_clear)
        self.checkBox_16 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_16.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Tool Button/resources/16.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_16.setIcon(icon5)
        self.checkBox_16.setIconSize(QtCore.QSize(23, 23))
        self.checkBox_16.setObjectName("checkBox_16")
        self.horizontalLayout.addWidget(self.checkBox_16)
        self.lcdNumber_readNum = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_readNum.setObjectName("lcdNumber_readNum")
        self.horizontalLayout.addWidget(self.lcdNumber_readNum)
        self.lcdNumber_writeNum = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_writeNum.setObjectName("lcdNumber_writeNum")
        self.horizontalLayout.addWidget(self.lcdNumber_writeNum)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_search.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Tool Button/resources/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_search.setIcon(icon6)
        self.pushButton_search.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_search.setFlat(True)
        self.pushButton_search.setObjectName("pushButton_search")
        self.horizontalLayout.addWidget(self.pushButton_search)
        self.comboBox_Com = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.comboBox_Com.setFont(font)
        self.comboBox_Com.setStyleSheet("")
        self.comboBox_Com.setObjectName("comboBox_Com")
        self.comboBox_Com.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_Com)
        self.comboBox_baud = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.comboBox_baud.setFont(font)
        self.comboBox_baud.setStyleSheet("")
        self.comboBox_baud.setObjectName("comboBox_baud")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_baud)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_read = QtWidgets.QWidget()
        self.page_read.setObjectName("page_read")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_read)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textEdit_read = QtWidgets.QTextEdit(self.page_read)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.textEdit_read.setFont(font)
        self.textEdit_read.setReadOnly(True)
        self.textEdit_read.setObjectName("textEdit_read")
        self.verticalLayout_2.addWidget(self.textEdit_read)
        self.stackedWidget.addWidget(self.page_read)
        self.page_write = QtWidgets.QWidget()
        self.page_write.setObjectName("page_write")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_write)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textEdit_write = QtWidgets.QTextEdit(self.page_write)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.textEdit_write.setFont(font)
        self.textEdit_write.setObjectName("textEdit_write")
        self.verticalLayout_3.addWidget(self.textEdit_write)
        self.stackedWidget.addWidget(self.page_write)
        self.verticalLayout.addWidget(self.stackedWidget)
        MyUART.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MyUART)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MyUART.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MyUART)
        self.statusbar.setObjectName("statusbar")
        MyUART.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MyUART)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MyUART)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionSelect_All = QtWidgets.QAction(MyUART)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionRecieve = QtWidgets.QAction(MyUART)
        self.actionRecieve.setObjectName("actionRecieve")
        self.actionSubmit = QtWidgets.QAction(MyUART)
        self.actionSubmit.setObjectName("actionSubmit")
        self.actionPreferences = QtWidgets.QAction(MyUART)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionMiniMize = QtWidgets.QAction(MyUART)
        self.actionMiniMize.setObjectName("actionMiniMize")
        self.actionAbout = QtWidgets.QAction(MyUART)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuView.addAction(self.actionRecieve)
        self.menuView.addAction(self.actionSubmit)
        self.menuSettings.addAction(self.actionPreferences)
        self.menuWindow.addAction(self.actionMiniMize)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MyUART)
        QtCore.QMetaObject.connectSlotsByName(MyUART)

    def retranslateUi(self, MyUART):
        _translate = QtCore.QCoreApplication.translate
        MyUART.setWindowTitle(_translate("MyUART", "MyUART"))
        self.comboBox_Com.setItemText(0, _translate("MyUART", "COM1"))
        self.comboBox_baud.setItemText(0, _translate("MyUART", "1200"))
        self.comboBox_baud.setItemText(1, _translate("MyUART", "2400"))
        self.comboBox_baud.setItemText(2, _translate("MyUART", "4800"))
        self.comboBox_baud.setItemText(3, _translate("MyUART", "9600"))
        self.comboBox_baud.setItemText(4, _translate("MyUART", "14400"))
        self.comboBox_baud.setItemText(5, _translate("MyUART", "19200"))
        self.comboBox_baud.setItemText(6, _translate("MyUART", "38400"))
        self.comboBox_baud.setItemText(7, _translate("MyUART", "43000"))
        self.comboBox_baud.setItemText(8, _translate("MyUART", "57600"))
        self.comboBox_baud.setItemText(9, _translate("MyUART", "76800"))
        self.comboBox_baud.setItemText(10, _translate("MyUART", "115200"))
        self.comboBox_baud.setItemText(11, _translate("MyUART", "128000"))
        self.comboBox_baud.setItemText(12, _translate("MyUART", "230400"))
        self.comboBox_baud.setItemText(13, _translate("MyUART", "256000"))
        self.comboBox_baud.setItemText(14, _translate("MyUART", "460800"))
        self.comboBox_baud.setItemText(15, _translate("MyUART", "921600"))
        self.menuFile.setTitle(_translate("MyUART", "File"))
        self.menuEdit.setTitle(_translate("MyUART", "Edit"))
        self.menuView.setTitle(_translate("MyUART", "View"))
        self.menuSettings.setTitle(_translate("MyUART", "Settings"))
        self.menuWindow.setTitle(_translate("MyUART", "Window"))
        self.menuHelp.setTitle(_translate("MyUART", "Help"))
        self.actionSave.setText(_translate("MyUART", "Save"))
        self.actionSave_As.setText(_translate("MyUART", "Save As..."))
        self.actionSelect_All.setText(_translate("MyUART", "Select All"))
        self.actionRecieve.setText(_translate("MyUART", "Recieve"))
        self.actionSubmit.setText(_translate("MyUART", "Submit"))
        self.actionPreferences.setText(_translate("MyUART", "Preferences..."))
        self.actionMiniMize.setText(_translate("MyUART", "MiniMize"))
        self.actionAbout.setText(_translate("MyUART", "About..."))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MyUART = QtWidgets.QMainWindow()
    ui = Ui_MyUART()
    ui.setupUi(MyUART)
    MyUART.show()
    sys.exit(app.exec_())
